version: '3.3'
services:
  kaldi:
    build: 
      context: "./kaldi/"
  web:
    build: 
      context: "./web/"
    volumes:
      - ${PWD}/servers.json:/server/servers.json
    ports:
      - "8080:8080"